version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r development.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run unit tests
          command: |
            source venv/bin/activate
            #python manage.py test --exclude-tag functional_test

#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
#
